volders/lib/volders_web/router.ex
defmodule VoldersWeb.Router do
  use VoldersWeb, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session  # Add this
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {VoldersWeb.LayoutView, :private}
    plug Coherence.Authentication.Session, protected: true  # Add this
  end

  # Add this block
  scope "/" do
    pipe_through :browser
    coherence_routes()

    # /sessions/new alias
    get "/login", Coherence.SessionController, :new
    get "/signup", Coherence.RegistrationController, :new
  end

  # Add this block
  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", VoldersWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/", VoldersWeb do
    pipe_through :protected
    # Add protected routes below
    resources "/contracts", ContractController
  end
end

volders/lib/volders_web/views/shared_view.ex
defmodule VoldersWeb.SharedView do
  use VoldersWeb, :view
end

volders/lib/volders_web/templates/shared/_footer.html.eex
<footer>
  <div class="">
    <p>All rights reserved</p>
  </div>
</footer>

volders/lib/volders_web/templates/shared/_header.html.eex
<header class="transparent">
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <%= link to: "/" do %>
          <%= img_tag(static_path(@conn, "/images/volders-logo-negative.svg")) %>
        <% end %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= if @conn.assigns[:current_user] do %>
            <li><%= link("Log out (#{Coherence.current_user_name(@conn)})", to: session_path(@conn, :delete), method: :delete, class: "btn btn-success") %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

volders/lib/volders_web/templates/shared/_private_header.html.eex
<header class="header">
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <%= link to: "/" do %>
          <%= img_tag(static_path(@conn, "/images/volders-logo-negative.svg")) %>
        <% end %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= if @conn.assigns[:current_user] do %>
            <li><%= link("Log out (#{Coherence.current_user_name(@conn)})", to: session_path(@conn, :delete), method: :delete, class: "btn btn-success") %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>